name: Canvas UI v2 - Jest tests

on:
  push:
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    # - name: Cache Node.js modules
    #   uses: actions/cache@v2
    #   id: yarn-cache 
    #   with:
    #     path: '**/node_modules'
    #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn build
    - name: Run linting
      run: yarn lint
    - name: Run tests
      run: yarn test:ci
